### PR TITLE
Idnames

### PR DESCRIPTION
**Pull request by alicerobson**
addresses issue  #5

### CODE REVIEW

**Comment by cbernet** [comment]
retest this please

**Comment by alicerobson** [comment]
retest this please

**Comment by alicerobson** [comment]
retest this please

**Comment by jlingema** [comment]
You updated the `init.sh` not the `README` ;-), maybe you can fix the commit message.

FYI: For members of HEP-FCC PRs are automatically retested after you push. For non-members: If we initiate the testing with "ok to test", it will also automatically retest changes, if we write "test this please" it only tests the current state and later changes have to be retested with "retest this please"

**Comment by alicerobson** [comment]
Hi Joschka
So I don’t have permissions to ask for a test/retest?

In the last commit, I  changed the instructions in the  readme  for running Papas. I didn’t alter the init.sh file. 

Does Jenkins automatically pick up the  instructions in the README file, or do I need to ask you  to update the commands? It needs to use source /afs/cern.ch/exp/fcc/sw/0.8pre/setup.sh <http://cern.ch/exp/fcc/sw/0.8pre/setup.sh> not version 7.
Thanks
Alice

**Comment by jlingema** [comment]
Hi Alice,
Sorry, I thought it was the init, since that's where usually the fcc-init script is sourced if it is needed. Indeed the Jenkins job has this currently hard-coded. I changed it now, but maybe it'd be better to put it inside the init script?

As for your permissions: You are allowed to ask for a retest (since you are a team member), but it's not necessary as Jenkins will do it automatically :)
Cheers,
Joschka

**Comment by cbernet** [comment]
Hi @jlingema isn't the check stuck?

**Comment by jlingema** [comment]
Yes, the Jenkins instance was restarted without prior notice... the comments about retesting were aimed at the comments before that. Sorry if I caused more confusion than explaining things :-S

retest this please

**Comment by jlingema** [comment]
And now I made a mistake :) 
retest this please

**Comment by jlingema** [comment]
OK, obviously I don't know enough to make this work. This is the current Jenkins configuration, anything I am still missing?

```
touch $WORKSPACE/controlfile
cd fcc-papas
source /cvmfs/fcc.cern.ch/sw/0.8pre/setup.sh
source ./init.sh
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=../install ..
make
make install
export CTEST_OUTPUT_ON_FAILURE=1
make test
```

**Comment by cbernet** [comment]
Shooting in the dark… 
do you really want to base this on 0.8pre?

**Comment by jlingema** [comment]
Hi Alice,

It was failing because it could not find one of the executables for the test (since I didn't source the project-init and, therefore, FCCPAPAS was not set). 

The log you can find by clicking on the little red cross next to the commit, then selecting the build (default in this case) and then on the left hand panel there should be links to the Output and Parsed Output.

The cvmfs installation can be setup as you see in my lines above, simply sourcing the initialization script there. The fcc.cern.ch file system is auto-mounted on lxplus machines once you try to access it.

retest this please

Cheers,
Joschka

**Comment by alicerobson** [comment]
Hi Colin, Branch idnames has finally passed its checks :-). Are you able to merge?
Alice

**Pull request merged**
