### PR TITLE
Simplify CMake Configuration

### PR DESCRIPTION
**Pull request by JavierCVilla**
- Apply similar changes submitted to [fcc-edm](https://github.com/HEP-FCC/fcc-edm/pull/62) and [podio](https://github.com/HEP-FCC/podio/pull/68) in order to clean the cmake configuration.
- Allow tests to run after the build phase rather than after the installation.

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi Colin,
seems I don't have write access to this repo. Can you take a look at this PR @cbernet ?
Cheers,
Valentin

**Comment by cbernet** [comment]
Hi Valentin,

I’ve just sent you an invitation to become collaborator to this repo, and set you admin.
Could you please confirm it works?

Cheers,

Colin

On 22 Jan 2019, at 13:02, vvolkl <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Colin,
seems I don't have write access to this repo. Can you take a look at this PR @cbernet<https://github.com/cbernet> ?
Cheers,
Valentin

**Comment by vvolkl** [comment]
Hi Colin,

no sorry, I didn't receive any invitation yet! I still can't merge either. Which email did you specify?
Cheers,
Valentin
________________________________

**Comment by vvolkl** [comment]
Now it worked, thanks :)
________________________________

**Pull request merged**
